/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir_salon;

/**
 *
 * @author Lina Aulia
 */
public class KasirSalonn extends javax.swing.JFrame {
        int jumlah1,Tota1,jumlah2, total2, jumlah3, total3, jumlah4, total4,total1;
  
    public KasirSalonn() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfHairSpa = new javax.swing.JCheckBox();
        TfHairMask = new javax.swing.JCheckBox();
        TfCreambath = new javax.swing.JCheckBox();
        TfHairCut = new javax.swing.JCheckBox();
        TfJhairspa = new javax.swing.JTextField();
        TfJhairmask = new javax.swing.JTextField();
        TfJcreambath = new javax.swing.JTextField();
        TfJhaircut = new javax.swing.JTextField();
        Total = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        TfOutput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfHairSpa.setBackground(new java.awt.Color(255, 255, 255));
        TfHairSpa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfHairSpa.setAlignmentX(2.0F);
        TfHairSpa.setAlignmentY(2.0F);
        TfHairSpa.setBorder(null);
        TfHairSpa.setPreferredSize(new java.awt.Dimension(30, 30));
        TfHairSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfHairSpaMouseClicked(evt);
            }
        });
        TfHairSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHairSpaActionPerformed(evt);
            }
        });
        getContentPane().add(TfHairSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 20, 30));

        TfHairMask.setBackground(new java.awt.Color(255, 255, 255));
        TfHairMask.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfHairMask.setAlignmentX(0.5F);
        TfHairMask.setMaximumSize(new java.awt.Dimension(77, 77));
        TfHairMask.setMinimumSize(new java.awt.Dimension(77, 77));
        TfHairMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHairMaskActionPerformed(evt);
            }
        });
        getContentPane().add(TfHairMask, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 20, 30));

        TfCreambath.setBackground(new java.awt.Color(255, 255, 255));
        TfCreambath.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfCreambath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCreambathActionPerformed(evt);
            }
        });
        getContentPane().add(TfCreambath, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 20, 30));

        TfHairCut.setBackground(new java.awt.Color(255, 255, 255));
        TfHairCut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfHairCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHairCutActionPerformed(evt);
            }
        });
        getContentPane().add(TfHairCut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 20, 30));
        getContentPane().add(TfJhairspa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 40, 40));
        getContentPane().add(TfJhairmask, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 40, 40));

        TfJcreambath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfJcreambathActionPerformed(evt);
            }
        });
        getContentPane().add(TfJcreambath, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 40, 40));
        getContentPane().add(TfJhaircut, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 40, 40));

        Total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Total.setText("Total");
        Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalMouseClicked(evt);
            }
        });
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 90, 50));

        Reset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 90, 50));

        TfOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfOutputActionPerformed(evt);
            }
        });
        getContentPane().add(TfOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 280, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lina Aulia\\Pictures\\mbul1.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfHairSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHairSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairSpaActionPerformed

    private void TfHairMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHairMaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairMaskActionPerformed

    private void TfCreambathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCreambathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCreambathActionPerformed

    private void TfJcreambathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfJcreambathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfJcreambathActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void TfHairSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfHairSpaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairSpaMouseClicked
 
    private void TotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalMouseClicked
    String Perawatan;
    Kata awal =new Kata();
    Perawatan ="";// TODO add your handling code here:
    if (TfHairSpa.isSelected()) {
        Perawatan += TfHairSpa.getText() + ", "; 
       jumlah1= Integer.parseInt(TfJhairspa.getText());
       total1 = jumlah1*25000;
    }
    if (TfHairMask.isSelected()) {
        Perawatan += TfHairMask.getText() + ", ";
        jumlah2= Integer.parseInt(TfJhairmask.getText ());
        total2 = jumlah2*30000;
    }
    if (TfCreambath.isSelected()) {
        Perawatan += TfCreambath.getText() + ", ";
        jumlah3= Integer.parseInt(TfJcreambath.getText ());
        total3 = jumlah3*35000;
    }
    if (TfHairCut.isSelected()) {
        Perawatan += TfHairCut.getText() + ", ";
        jumlah4= Integer.parseInt(TfJhaircut.getText ());
        total4 = jumlah4*15000;
    }
    TfOutput.setText (awal.Awal()+""+(total1+total2+total3+total4));
    }//GEN-LAST:event_TotalMouseClicked

    private void TfHairCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHairCutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairCutActionPerformed

    private void TfOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfOutputActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        TfHairSpa.setSelected(false);
        TfHairMask.setSelected(false);
        TfCreambath.setSelected(false);
        TfHairCut.setSelected(false);
        TfJhairspa.setText ("");
        TfJhairmask.setText ("");
        TfJcreambath.setText ("");
        TfJhaircut.setText ("");
        TfOutput.setText ("");// TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirSalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JCheckBox TfCreambath;
    private javax.swing.JCheckBox TfHairCut;
    private javax.swing.JCheckBox TfHairMask;
    private javax.swing.JCheckBox TfHairSpa;
    private javax.swing.JTextField TfJcreambath;
    private javax.swing.JTextField TfJhaircut;
    private javax.swing.JTextField TfJhairmask;
    private javax.swing.JTextField TfJhairspa;
    private javax.swing.JTextField TfOutput;
    private javax.swing.JButton Total;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
