/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir_salon;

/**
 *
 * @author Lina Aulia
 */
public class KasirSalon extends javax.swing.JFrame {
        int jumlah1,Tota1,jumlah2, total2, jumlah3, total3, jumlah4, total4,total1;
    /**TfHairMask.getText() 
     * Creates new form KasirSalon
     */
    public KasirSalon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfHairSpa = new javax.swing.JCheckBox();
        TfHairMask = new javax.swing.JCheckBox();
        TfCreambath = new javax.swing.JCheckBox();
        TfHairCut = new javax.swing.JCheckBox();
        TfJhairspa = new javax.swing.JTextField();
        Total = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        TfOutput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfHairSpa.setBackground(new java.awt.Color(255, 255, 255));
        TfHairSpa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfHairSpa.setAlignmentX(2.0F);
        TfHairSpa.setAlignmentY(2.0F);
        TfHairSpa.setBorder(null);
        TfHairSpa.setPreferredSize(new java.awt.Dimension(30, 30));
        TfHairSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfHairSpaMouseClicked(evt);
            }
        });
        TfHairSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHairSpaActionPerformed(evt);
            }
        });
        getContentPane().add(TfHairSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 20, 30));

        TfHairMask.setBackground(new java.awt.Color(255, 255, 255));
        TfHairMask.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfHairMask.setAlignmentX(0.5F);
        TfHairMask.setMaximumSize(new java.awt.Dimension(77, 77));
        TfHairMask.setMinimumSize(new java.awt.Dimension(77, 77));
        TfHairMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHairMaskActionPerformed(evt);
            }
        });
        getContentPane().add(TfHairMask, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 20, 30));

        TfCreambath.setBackground(new java.awt.Color(255, 255, 255));
        TfCreambath.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfCreambath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCreambathActionPerformed(evt);
            }
        });
        getContentPane().add(TfCreambath, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 20, 30));

        TfHairCut.setBackground(new java.awt.Color(255, 255, 255));
        TfHairCut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TfHairCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHairCutActionPerformed(evt);
            }
        });
        getContentPane().add(TfHairCut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 20, 30));

        TfJhairspa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfJhairspaActionPerformed(evt);
            }
        });
        getContentPane().add(TfJhairspa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 40, 40));

        Total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Total.setText("Total");
        Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalMouseClicked(evt);
            }
        });
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, 40));

        Reset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, 40));

        TfOutput.setKeymap(null);
        TfOutput.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TfOutputComponentRemoved(evt);
            }
        });
        TfOutput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfOutputFocusLost(evt);
            }
        });
        TfOutput.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                TfOutputComponentHidden(evt);
            }
        });
        TfOutput.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                TfOutputCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TfOutputInputMethodTextChanged(evt);
            }
        });
        TfOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfOutputActionPerformed(evt);
            }
        });
        TfOutput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfOutputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfOutputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfOutputKeyTyped(evt);
            }
        });
        getContentPane().add(TfOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 260, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lina Aulia\\Pictures\\mbul1.jpg")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfHairSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHairSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairSpaActionPerformed

    private void TfHairMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHairMaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairMaskActionPerformed

    private void TfCreambathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCreambathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCreambathActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void TfHairSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfHairSpaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairSpaMouseClicked
 
    private void TotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalMouseClicked
    //Menampilkan data ke jumlah biaya
        String Perawatan;
    Kata awal = new Kata();
    Perawatan ="0";
// TODO add your handling code here:
    if (TfHairSpa.isSelected()) {
        Perawatan += TfHairSpa.getText() + ", "; 
       jumlah1= Integer.parseInt(TfJhairspa.getText());
       total1 = jumlah1*25000;
      
    }
    if (TfHairMask.isSelected()) {
        Perawatan += TfHairMask.getText() + ", ";
        jumlah2= Integer.parseInt(TfJhairspa.getText ());
        total2 = jumlah2*30000;
        
    }
    if (TfCreambath.isSelected()) {
        Perawatan += TfCreambath.getText() + ", ";
        jumlah3= Integer.parseInt(TfJhairspa.getText ());
        total3 = jumlah3*35000;
    }
    if (TfHairCut.isSelected()) {
        Perawatan += TfHairCut.getText() + ", ";
        jumlah4= Integer.parseInt(TfJhairspa.getText ());
        total4 = jumlah4*15000;
    }
    TfOutput.setText (awal.Awal()+"\n "+(total1+total2+total3+total4)); 
    
    }//GEN-LAST:event_TotalMouseClicked

    private void TfHairCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHairCutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHairCutActionPerformed

    private void TfOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfOutputActionPerformed
              // TODO add your handling code here:
            
    }//GEN-LAST:event_TfOutputActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        TfHairSpa.setSelected(false);
        TfHairMask.setSelected(false);
        TfCreambath.setSelected(false);
        TfHairCut.setSelected(false);
        total1=0;
        total2=0;
        total3=0;
        total4=0;
        TfJhairspa.setText (" ");
        TfOutput.setText (" ");// TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void TfJhairspaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfJhairspaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfJhairspaActionPerformed

    private void TfOutputComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TfOutputComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputComponentRemoved

    private void TfOutputComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TfOutputComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputComponentHidden

    private void TfOutputInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TfOutputInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputInputMethodTextChanged

    private void TfOutputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfOutputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputKeyTyped

    private void TfOutputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfOutputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputKeyReleased

    private void TfOutputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfOutputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputKeyPressed

    private void TfOutputCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TfOutputCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputCaretPositionChanged

    private void TfOutputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfOutputFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TfOutputFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirSalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JCheckBox TfCreambath;
    private javax.swing.JCheckBox TfHairCut;
    private javax.swing.JCheckBox TfHairMask;
    private javax.swing.JCheckBox TfHairSpa;
    private javax.swing.JTextField TfJhairspa;
    private javax.swing.JTextField TfOutput;
    private javax.swing.JButton Total;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
